### ISSUE TITLE
.sort() with .all() doesn't work

### ISSUE THREAD

**Issue by jortizsao** [sphereio/sphere-node-sdk#122]
If we make a query with .alI() and then .sort() by some field the results are not sorted. 
i.e 

```
return client.orders
      .where(`createdAt > "${date}"`)
      .sort('createdAt', true)
      .all()
      .fetch().then((res) => {
        return res.body.results;
      });
```

Retrieves the following:
Order: 200000567, createdAt: 2016-04-13T10:01:18.660Z
Order: 200000578, createdAt: 2016-04-13T16:36:34.916Z
Order: 200000583, createdAt: 2016-04-19T19:10:59.523Z
Order: 200000558, createdAt: 2016-04-11T13:09:32.232Z
Order: 200000563, createdAt: 2016-04-12T19:36:40.710Z

If we remove the .all()

```
return client.orders
      .where(`createdAt > "${date}"`)
      .sort('createdAt', true)
      .fetch().then((res) => {
        return res.body.results;
      });
```

Retrieves the orders sorted:
Order: 200000553, createdAt: 2016-04-10T17:39:30.393Z
Order: 200000554, createdAt: 2016-04-10T17:44:23.793Z
Order: 200000555, createdAt: 2016-04-10T17:46:33.496Z
Order: 200000556, createdAt: 2016-04-10T17:50:43.261Z
Order: 200000557, createdAt: 2016-04-10T17:53:04.936Z

I guess that internally the SDK iterates over pages in order to retrieve all results as the API doesn't provide the 'all' feature but the final results IMHO should be sorted

**Comment by PhilippSpo** [comment]
Thanks for reporting this!
You are right, when using `all()` (which results in doing a paged request) you cannot use your own sorting. The reason for this is, that we must sort by id in order to do a paged request and know where we need to continue after each page.
You can alternatively use the [`process`](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L327) function instead of `all`:
```js
client.orders
.where(`createdAt > "${date}"`)
.sort('createdAt', true)
.process(result => Promise.resolve(result.body.results))
.then(results => {
  // This is a flat map
  // `[ [{}, {}], [{}, {}] ]`
})
```
If you can describe your use case and context a little more, we can maybe think of a even better / more efficient solution for your problem 😉

**Comment by jortizsao** [comment]
Hi Phillip, thanks for your quick response. here I describe two solutions that we can discuss:

1. The .all() function can do a paged a request as currently does, but instead of sorting only by 'id', should sort by 'params_sort_fields ' (there can be several) and 'id' as the last sort parameter. The API allows this: http://dev.commercetools.com/http-api.html#sorting, thus, you are confident that sort path is univocal and you won't get repeated results while paging.

2. If you don't agree with the first approach, you can leave the .all() as it is (sorted only by 'id'), but once you have all results, sort them using the sortBy function of underscore/lodash. The cool thing is that path used by underscore/lodash works with the same 'dot' notation as the Sphere SDK
i.e

``` javascript
_.sortBy(data, function(item) {
   return [item.sortData.a, item.sortData.b];
});

```
so the function could be simple ( the only thing remaining is that underscore/lodash only sort in ascending order but for descending order we can use something like sortBy(...).reverse() ) 

In my opinion the first solution is better and I don't see any drawback, But as I said before, I'm open to discuss or provide whatever you need from me. 

In terms of use cases, it's a pretty common scenario to get all results with some filter applied and sorted by some fields. Obviously, I can develop a workaround in order to get the expected behaviour, but IMHO the current behaviour is confusing because the SDK should hide the limitations of the API ( .all() feature is not provided natively) and intuitively you expect to get the results sorted even for 'all'.

**Comment by PhilippSpo** [comment]
OK we had some internal discussion about this, and figured that it is pretty easy to change this behaviour, so that you can pass your custom sorting. If you don't provide any sorting and do `all()` it will still sort by `id` then. We will probably release this today. We can then still think about whether it makes sense to also always append the `id` sorting. At the moment you would need to do that manually if you want, but sorting e.g. by `createdAt` should be sufficient.
Thank you again for reporting this issue! We love to get feedback to see which problems people have with the SDK and are happy to improve the developer experience as much as we can :)

**Comment by LEQADA** [comment]
This feature introduced an issue that independent from sorting field it would still paginate by `id` which leads to undetermined results.
For example `.all().sort("sku")` would not return all (only 650 of total 90000) inventory entries from inventory endpoint.

**Comment by LEQADA** [comment]
Related https://github.com/sphereio/sphere-stock-export/issues/11

**Comment by LEQADA** [comment]
Related https://github.com/sphereio/sphere-node-sdk/issues/194

**Comment by hisabimbola** [comment]
Since this issue created a bug, we should create another issue with the bug, and this issue can be referenced from that issue else we keep opening old issues. 

Closing this issue for that.

**Comment by LEQADA** [comment]
@hisabimbola https://github.com/sphereio/sphere-node-sdk/issues/194

**Comment by butenkor** [comment]
@hisabimbola The thing is that this not just introduced new bug it also never worked properly if you had more than 2 result pages.
