### ISSUE TITLE
scope is hardcoded on oauth2 service

### ISSUE THREAD

**Issue by esoliani** [sphereio/sphere-node-sdk#216]
The scope in oauth service is hardcoded to be manage_project, as follow:
```
scope: "manage_project:" + this._options.config.project_key
```
This should be configurable in this._options.config.scope with a default value.

**Comment by hisabimbola** [comment]
Hello @esoliani 

Thanks for reporting this.
Very valid that the scope should be configurable.
This issue will be prioritise and implemented as soon as possible 

Also be informed that we have a new module (sdk) that handles this [here](https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareAuth.html) and this issue is not a problem there

**Comment by emmenko** [comment]
This library will be deprecated soon. Please refer to the new SDK library / documentation https://commercetools.github.io/nodejs/sdk/

**Comment by ValeSauer** [comment]
@hisabimbola and @emmenko 
@esoliani needs this for a customer project that has only three weeks from now until scheduled release. Would be great if you could help him soon.

**Comment by hisabimbola** [comment]
Hello @ValeSauer @esoliani 

we would work on this, it should be ready before the end of this week.

Thanks

**Comment by emmenko** [comment]
Why can't you use the new sdk? It takes like 10min to migrate. We do not want to implement any new features in this library, only bug fixes.

**Comment by ValeSauer** [comment]
Did not know it is that easy to migrate. @esoliani please check if you could migrate without delay. It would be the far best option.

**Comment by hisabimbola** [comment]
Closing this issue since this is not valid again, please reopen and comment if otherwise
