### ISSUE TITLE
[order-sync] Fix adding new parcel to delivery

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-node-sdk#229]
### Description
There is an error in [order sync](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/sync/utils/order.coffee#L68) method which throws an error when adding a new delivery parcel to an old delivery and simultaneously adding new delivery which is placed before the old delivery in the delivery array.

**Old object**
```js
{
  orderNumber: 'peanutbutter jelly',
  shippingInfo: {
    deliveries: [{
      id: 'c65e0661-5db8-4183-bcbc-6a4551a26d5b',  // OLD DELIVERY
      createdAt: '2017-05-22T07:33:02.202Z',
      items: [{
        id: '4dc17170-30ad-4b95-9a83-1388b40f5a1e',
        quantity: 9001
      }],
      parcels: [{
        id: '25098a64-95f6-48dd-b7ea-095d8224cb8e',
        createdAt: '2017-05-22T07:33:02.202Z',
        trackingData: {
          trackingId: '447883009643',
          carrier: 'dhl',
          isReturn: false
        }
      }]
    }]
  }
}
```

**New object**
```js
{
  orderNumber: 'peanutbutter jelly',
  shippingInfo: {
    deliveries: [{
      id: '1', // NEW DELIVERY
      items: [{
        id: '4dc17170-30ad-4b95-9a83-1388b40f5a1e',
        quantity: 100
      }],
      parcels: [{
        id: '1',
        trackingData: {
          trackingId: '123456789',
          carrier: 'TEST',
          provider: 'provider 1',
          providerTransaction: 'provider transaction 1',
          isReturn: false
        },
        measurements: {
          lengthInMillimeter: 100,
          heightInMillimeter: 200,
          widthInMillimeter: 200,
          weightInGram: 500
        }
      }]
    }, {
      id: 'c65e0661-5db8-4183-bcbc-6a4551a26d5b', // OLD DELIVERY
      items: [{
        id: '4dc17170-30ad-4b95-9a83-1388b40f5a1e',
        quantity: 9001
      }],
      parcels: [{
        id: '222',
        trackingData: {
          trackingId: '123456789',
          carrier: 'DHL',
          provider: 'provider',
          providerTransaction: 'transaction provider',
          isReturn: false
        },
        measurements: {
          lengthInMillimeter: 100,
          heightInMillimeter: 200,
          widthInMillimeter: 200,
          weightInGram: 500
        }
      }, {
        id: '25098a64-95f6-48dd-b7ea-095d8224cb8e',
        createdAt: '2017-05-22T07:33:02.202Z',
        trackingData: {
          trackingId: '447883009643',
          carrier: 'dhl',
          isReturn: false
        }
      }]
    }]
  }
}
```

### Expected Behavior
It should build sync actions properly.

### Current Behavior
Getting an error message:
```sh
'TypeError: Cannot read property \'id\' of undefined
    at /Users/xjunajan/dev/commercetools/orders-update/node_modules/sphere-node-sdk/lib/sync/utils/order.js:79:71
```

**Comment by hisabimbola** [comment]
Pair programmed with @junajan on this, and we discovered some inconsistency in the order sync method.

Let's add this test cases to help ensure that common edge cases are covered

- should generate correct update actions when a new delivery is added to the new object
- should be agnostic of the index(position) of the deliveries in both new and order order object
- should generate correction update actions a new parcel has been added
- should work when no deliveries was existing in old order
- should work when only new deliveries are provided without providing existing deliveries in the old order object (this is possible for orders because it's *currently* not possible to remove deliveries from an order)
- should throw if there is no deliveryId in the new order object (check if consistent with similar implementations in other entities)
